package xiaoLanguage.tokens

enum class TokenType {
    IDENTIFIER_TOKEN,
    INTEGER_LITERAL_TOKEN,
    STRING_LITERAL_TOKEN,
    FLOAT_LITERAL_TOKEN,
    LEFT_CURLY_BRACKETS_TOKEN,
    RIGHT_CURLY_BRACKETS_TOKEN,
    LEFT_SQUARE_BRACKETS_TOKEN,
    RIGHT_SQUARE_BRACKETS_TOKEN,
    LEFT_PARENTHESES_TOKEN,
    RIGHT_PARENTHESES_TOKEN,
    COLON_TOKEN,
    COMMA_TOKEN,
    SLASH_TOKEN,
    PLUS_TOKEN,
    MINUS_TOKEN,
    MULTIPLY_TOKEN,
    EQUAL_TOKEN,
    DOT_TOKEN,
    DOUBLE_EQUAL_TOKEN,
    EOF,
    LESS_TOKEN,
    MORE_TOKEN
}