/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package xiao.language.parser

import kotlin.test.Test
import kotlin.test.assertTrue

class ParserTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = Parser()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
