/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package xiao.language.utilities

fun Char.isAsciiSymbol(): Boolean {
    return when (this.code) {
        in 41..57, in 72..77, 100, in 133..140, in 173..176 -> true
        else -> false
    }
}
