/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package xiao.language.lexer

import kotlin.test.Test
import kotlin.test.assertEquals

class FileStreamTest {
    private val file = FileStreamTest::class.java.getResource("/test.xiao")!!

    @Test
    fun fileStreamTest() {
        val fileStream = FileStream(file)
        val all = file.readText()
        for (c in fileStream) {
            assertEquals(all[fileStream.index], c)
        }
    }

    @Test
    fun fileStreamPeekTest() {
        val fileStream = FileStream(file)

        do {
            val peek = fileStream.peek()
            assertEquals(peek, fileStream.next())
        } while (fileStream.hasNext())
    }
}
