/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package xiao.language.utilities

import kotlin.test.Test

class UtilitiesTest {
    @Test
    fun charIsSymbolTest() {
        val symbols = ('!'..'/') + (':'..'@') + ('['..'`') + ('{'..'~')

        for (symbol in symbols) {
            assert(symbol.isAsciiSymbol())
        }
    }
}